# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-AwsEBS
env:
  EB_PACKAGE_S3_BUCKET_NAME: "flaskrobot"
  EB_APPLICATION_NAME: "flaskrobot"
  EB_ENVIRONMENT_NAME: "Flaskrobot-env"
  AWS_REGION_NAME: "ap-southeast-1"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Set up Python 3.8 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      #run tests    
      - name: Run unit tests
        run: |
          python test_robot.py

      # Runs a single command using the runners shell
      - name: Create zip deployment
        run: zip -r deploy.zip ./ -x '*.git*'
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Set up Python 3.6 environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
       
      # Elastic Beanstalk CLI version 
      - name: Get EB CLI version
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version
        
      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1
          
      # Create the Elastic Beanstalk application
      - name: Create EBS application
        run: |
          eb init -p python-3.8 flask-robot --region ap-southeast-1
          
      # Deploy to (or Create) the Elastic Beanstalk environment
      - name: Create test environment & deploy
        run: |
          (eb use test-environment2 && eb status test-environment2 && eb deploy) || eb create test-environment2    
